setwd("~/GitHub/ExData_Plotting1")
download.file("https://d396qusza40orc.cloudfront.net/exdata%2Fdata%2Fhousehold_power_consumption.zip",destfile = "./exdata-data-Fhousehold_power_consumption.zip",method="auto")
unzip("./exdata-data-Fhousehold_power_consumption.zip")
pdata <- read.table("./household_power_consumption.txt",header= TRUE , sep = ";", na.strings = c("?"))
## pdata <- read.table("./household_power_consumption.txt",header= TRUE , sep = ";")
pdata$DateTime <- strptime(paste(as.character(pdata$Date)," ",as.character(pdata$Time)), "%d/%m/%Y %H:%M:%S")
spdata <- subset (pdata, DateTime >= as.POSIXlt( "2007-02-01 00:00:00") & DateTime <= as.POSIXlt( "2007-02-02 00:00:00"))
hist(spdata$Global_active_power, breaks=12, col="red", main= "Global Active Power", xlab = "Global Active Power (kilowatts)" )
dev.copy(png, file = "plot1.png")
dev.off()
